name: Changeset Check

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  changeset-check:
    name: Check for Changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
