name: Dependabot Changesets

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  changeset:
    name: Add changeset to Dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.CHANGESET_GITHUB_TOKEN }}

      - name: Pull latest changes
        run: git pull --rebase origin ${{ github.event.pull_request.head.ref }}

      - uses: StafflinePeoplePlus/dependabot-changesets@v0.1.5
        with:
          owner: upstart-gg
          repo: lucerna
          pr-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.CHANGESET_GITHUB_TOKEN }}
